In [1]:
import numpy as np

In [2]:
def NUMPY_outer(X,Y):
    outer=np.zeros((len(X),len(Y)), dtype=int)
    for i in range(len(X)):
        for j in range(len(Y)):
            outer[i][j] = X[i]*Y[j]
    return outer
        

In [3]:
np.random.seed(24787)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)

In [4]:
np.outer(X,Y)

array([[ 288116,  433466,  322354, ...,  234498,  459306,  323646],
       [ 214972,  323422,  240518, ...,  174966,  342702,  241482],
       [-312200, -469700, -349300, ..., -254100, -497700, -350700],
       ...,
       [ 180184,  271084,  201596, ...,  146652,  287244,  202404],
       [ -66454,  -99979,  -74351, ...,  -54087, -105939,  -74649],
       [ 203376,  305976,  227544, ...,  165528,  324216,  228456]])

In [5]:
NUMPY_outer(X,Y)

array([[ 288116,  433466,  322354, ...,  234498,  459306,  323646],
       [ 214972,  323422,  240518, ...,  174966,  342702,  241482],
       [-312200, -469700, -349300, ..., -254100, -497700, -350700],
       ...,
       [ 180184,  271084,  201596, ...,  146652,  287244,  202404],
       [ -66454,  -99979,  -74351, ...,  -54087, -105939,  -74649],
       [ 203376,  305976,  227544, ...,  165528,  324216,  228456]])

In [6]:
NUMPY_outer(X,Y)==np.outer(X,Y)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

The built-in implementation by numpy is much faster because of how numpy manages its arrays, with homogeneous data types stored together in memory. Also due to how it integrates C/C++ code, which are faster than normal python. It also breaks down tasks into fragments and executes in parallel, so each row would be calculated in parallel in this excercise.