In [1]:
import numpy as np
import time

np.random.seed(24787)
a = np.random.randint(8, size=(3,4,4))

In [2]:
print(a)
print('Shape of a: ',a.shape)

[[[2 6 4 1]
  [0 4 4 3]
  [6 6 1 2]
  [7 0 6 5]]

 [[1 3 3 7]
  [4 7 2 5]
  [0 4 6 7]
  [5 5 7 1]]

 [[7 2 4 5]
  [6 7 7 0]
  [6 2 0 4]
  [2 0 7 6]]]
Shape of a:  (3, 4, 4)


In [3]:
fours = np.where(a==4)
#Print indices, first array is depth, second is row, third is column.
print(fours)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 1, 1, 2, 0, 2]), array([2, 1, 2, 0, 1, 2, 3]))


In [4]:
b = np.tile(a,(2,2))
b.shape

(3, 8, 8)

In [5]:
c = b.sum(axis=0)

print(c)
print('Shape of c: ',c.shape)

[[10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]
 [10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]]
Shape of c:  (8, 8)


In [6]:
np.random.seed(24787)
a = np.random.randint(8, size=(1000,1000))
b = np.random.randint(8, size=(1000,1000))

In [7]:
def matmul(a,b):
    product = np.zeros(a.shape)
    for x in range(a.shape[0]):
        for i in range(a.shape[0]):
            for j in range(a.shape[1]):
                product[i,x] += a[i,j]*b[j,x]
                
    return product
            

In [8]:
start = time.time()
c = matmul(a,b)
print("Multiplication took: ", time.time()-start, " seconds.")

Multiplication took:  515.9055788516998  seconds.


In [9]:
start = time.time()
d = a@b
print("Multiplication took: ", time.time()-start, " seconds.")

Multiplication took:  0.7417197227478027  seconds.


In [10]:
c==d

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

Numpy is generally faster than python because it runs its functions with C and Fortran (static languages), because dynamic languages (like Python) are slow for loops anf callinf functions.